import type { Product, Testimonial } from "@/types";

export const products: Product[] = [
  {
    id: "inv-5kw",
    name: "VoltMax 5kW Hybrid Inverter",
    category: "inverter",
    price: 1299,
    originalPrice: 1599,
    power: "5000W",
    efficiency: "97.6%",
    warranty: "5 years",
    badge: "Best Seller",
    features: [
      "MPPT solar charge controller",
      "Pure sine wave output",
      "Wi-Fi monitoring app",
      "Grid-tie & off-grid modes",
      "LCD touch display",
    ],
    image: "/products/inverter-5kw.svg",
  },
  {
    id: "inv-10kw",
    name: "VoltMax 10kW Pro Inverter",
    category: "inverter",
    price: 2199,
    power: "10000W",
    efficiency: "98.2%",
    warranty: "5 years",
    features: [
      "Dual MPPT tracking",
      "Three-phase output",
      "Remote firmware updates",
      "Generator auto-start",
      "IP65 weatherproof",
    ],
    image: "/products/inverter-10kw.svg",
  },
  {
    id: "bat-10kwh",
    name: "PowerCell 10kWh LiFePO4",
    category: "battery",
    price: 3499,
    originalPrice: 3999,
    capacity: "10kWh",
    efficiency: "96%",
    warranty: "10 years",
    badge: "Most Popular",
    features: [
      "6000+ charge cycles",
      "Built-in BMS",
      "Stackable up to 60kWh",
      "Temperature management",
      "99% depth of discharge",
    ],
    image: "/products/battery-10kwh.svg",
  },
  {
    id: "bat-20kwh",
    name: "PowerCell 20kWh LiFePO4",
    category: "battery",
    price: 6499,
    capacity: "20kWh",
    efficiency: "96%",
    warranty: "10 years",
    features: [
      "6000+ charge cycles",
      "Built-in BMS",
      "Modular expansion",
      "Smart load balancing",
      "Fire-safe chemistry",
    ],
    image: "/products/battery-20kwh.svg",
  },
  {
    id: "sol-400w",
    name: "SunPower 400W Mono Panel",
    category: "solar",
    price: 299,
    efficiency: "22.3%",
    power: "400W",
    warranty: "25 years",
    badge: "Top Rated",
    features: [
      "Monocrystalline PERC cells",
      "Anti-reflective coating",
      "Wind load 2400 Pa",
      "Half-cut cell technology",
      "IP68 junction box",
    ],
    image: "/products/solar-400w.svg",
  },
  {
    id: "sol-550w",
    name: "SunPower 550W Bifacial Panel",
    category: "solar",
    price: 399,
    efficiency: "23.1%",
    power: "550W",
    warranty: "25 years",
    features: [
      "Bifacial double glass",
      "25-year performance guarantee",
      "Anti-PID technology",
      "Salt mist resistant",
      "Ultra-low degradation",
    ],
    image: "/products/solar-550w.svg",
  },
];

export const testimonials: Testimonial[] = [
  {
    id: "t1",
    name: "Marcus Johnson",
    location: "Phoenix, AZ",
    rating: 5,
    text: "After installing the VoltMax 5kW inverter with two PowerCell batteries, our home runs entirely on solar during the day. Our electricity bill dropped by 90%. Best investment we've made.",
    avatar: "MJ",
    product: "VoltMax 5kW + PowerCell 20kWh",
  },
  {
    id: "t2",
    name: "Sarah Chen",
    location: "Austin, TX",
    rating: 5,
    text: "We had three blackouts last summer — never an issue since installing VoltHouse. The Wi-Fi monitoring app is excellent, I can see everything from my phone.",
    avatar: "SC",
    product: "VoltMax 10kW Pro",
  },
  {
    id: "t3",
    name: "David Rivera",
    location: "Miami, FL",
    rating: 5,
    text: "Hurricane season doesn't scare us anymore. 20kWh of storage kept our fridge, AC, and medical equipment running for 48 hours straight. Incredible system.",
    avatar: "DR",
    product: "PowerCell 20kWh + SunPower 550W",
  },
  {
    id: "t4",
    name: "Emily Thompson",
    location: "San Diego, CA",
    rating: 5,
    text: "The SunPower bifacial panels exceed their rated output on our roof. Installation team was professional and finished in a single day. Highly recommend.",
    avatar: "ET",
    product: "SunPower 550W Bifacial (×12)",
  },
];
