import type { Product, Testimonial } from "@/types";

export const products: Product[] = [
  {
    id: "inv-5kw",
    name: "VoltMax 5kW Hybrid Inverter",
    category: "inverter",
    price: 1299,
    originalPrice: 1599,
    power: "5000W",
    efficiency: "97.6%",
    warranty: "5 years",
    badge: "Хіт продажів",
    features: [
      "MPPT сонячний контролер заряду",
      "Чиста синусоїда на виході",
      "Додаток для моніторингу через Wi-Fi",
      "Мережевий та автономний режими",
      "РК сенсорний дисплей",
    ],
    image: "/products/inverter-5kw.svg",
  },
  {
    id: "inv-10kw",
    name: "VoltMax 10kW Pro Inverter",
    category: "inverter",
    price: 2199,
    power: "10000W",
    efficiency: "98.2%",
    warranty: "5 years",
    features: [
      "Подвійне відстеження MPPT",
      "Трифазний вихід",
      "Віддалені оновлення прошивки",
      "Автозапуск генератора",
      "Захист IP65 від погодних умов",
    ],
    image: "/products/inverter-10kw.svg",
  },
  {
    id: "bat-10kwh",
    name: "PowerCell 10kWh LiFePO4",
    category: "battery",
    price: 3499,
    originalPrice: 3999,
    capacity: "10kWh",
    efficiency: "96%",
    warranty: "10 years",
    badge: "Найпопулярніший",
    features: [
      "6000+ циклів заряду",
      "Вбудована BMS",
      "Модульне нарощування до 60 кВт·год",
      "Управління температурою",
      "99% глибина розряду",
    ],
    image: "/products/battery-10kwh.svg",
  },
  {
    id: "bat-20kwh",
    name: "PowerCell 20kWh LiFePO4",
    category: "battery",
    price: 6499,
    capacity: "20kWh",
    efficiency: "96%",
    warranty: "10 years",
    features: [
      "6000+ циклів заряду",
      "Вбудована BMS",
      "Модульне розширення",
      "Розумне балансування навантаження",
      "Пожежобезпечна хімія",
    ],
    image: "/products/battery-20kwh.svg",
  },
  {
    id: "sol-400w",
    name: "SunPower 400W Mono Panel",
    category: "solar",
    price: 299,
    efficiency: "22.3%",
    power: "400W",
    warranty: "25 years",
    badge: "Найвищий рейтинг",
    features: [
      "Монокристалічні PERC клітини",
      "Антивідблискове покриття",
      "Навантаження вітру 2400 Па",
      "Технологія напівзрізаних клітин",
      "З'єднувальна коробка IP68",
    ],
    image: "/products/solar-400w.svg",
  },
  {
    id: "sol-550w",
    name: "SunPower 550W Bifacial Panel",
    category: "solar",
    price: 399,
    efficiency: "23.1%",
    power: "550W",
    warranty: "25 years",
    features: [
      "Двостороннє подвійне скло",
      "Гарантія продуктивності 25 років",
      "Технологія Anti-PID",
      "Стійкість до сольового туману",
      "Надзвичайно низька деградація",
    ],
    image: "/products/solar-550w.svg",
  },
];

export const testimonials: Testimonial[] = [
  {
    id: "t1",
    name: "Максим Коваленко",
    location: "Київ",
    rating: 5,
    text: "Після встановлення інвертора VoltMax 5kW з двома акумуляторами PowerCell наш будинок вдень повністю живиться від сонця. Рахунок за електроенергію зменшився на 90%. Найкраща інвестиція, яку ми зробили.",
    avatar: "МК",
    product: "VoltMax 5kW + PowerCell 20kWh",
  },
  {
    id: "t2",
    name: "Оксана Мельник",
    location: "Харків",
    rating: 5,
    text: "Минулої зими у нас були постійні відключення електроенергії — тепер про це забули після встановлення VoltHouse. Додаток для моніторингу через Wi-Fi чудовий — бачу все зі свого телефону.",
    avatar: "ОМ",
    product: "VoltMax 10kW Pro",
  },
  {
    id: "t3",
    name: "Дмитро Іванченко",
    location: "Дніпро",
    rating: 5,
    text: "Відключення вже нас не лякають. 20 кВт·год накопичувача тримали холодильник, опалення та медичне обладнання протягом 48 годин поспіль. Неймовірна система.",
    avatar: "ДІ",
    product: "PowerCell 20kWh + SunPower 550W",
  },
  {
    id: "t4",
    name: "Олена Шевченко",
    location: "Львів",
    rating: 5,
    text: "Двосторонні панелі SunPower перевищують заявлену потужність на нашому даху. Команда монтажників була дуже професійною та завершила роботу за один день. Дуже рекомендую.",
    avatar: "ОШ",
    product: "SunPower 550W Bifacial (×12)",
  },
];
